### ISSUE TITLE
Pseudo-randomisatie stimuli op basis van criteria

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/jspsych-vislexdec-vp#10]
Het zou erg fijn zijn om stimuli te kunnen pseudorandomiseren op basis van criteria (niet meer dan twee items in conditie X na elkaar, niet meer dan drie experimentele items na elkaar, etc). 

Als dat niet kan doen we het in de cursus op de oldskool-wijze van met de hand een volgorde maken en die ook in de omgekeerde volgorde aanbieden om leereffecten te voorkomen. Dat is wel foutgevoelig, zeker als er meerdere lijsten zijn.

**Comment by maartenuni** [comment]
@irisopgithub is dit issue nummer 10 anders dan issue #9 ? Anders wil ik deze sluiten en 9 aanpakken mits dat haalbaar is.

**Comment by irisopgithub** [comment]
is hetzelfde, github-hikje. (issue wou niet posten en toen had ik er blijkbaar opeens twee, niet gezien sorry)
