### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/jspsych-vislexdec-vp#12]
Mooie heldere tekst, petje af.

In de bijlage tiepfouten met track changes, en een paar kleine suggesties.

[readmeLDVP.docx](https://github.com/UiL-OTS-labs/jspsych-vislexdec-vp/files/5408262/readmeLDVP.docx)

**Comment by jcvanelst** [comment]
Ik heb deze zo goed ik kan verwerkt en nog een voorzet gedaan om de 'pairing' van prime en 'test stimulus' te beschrijven, maar sta open voor betere duiding. Je kunt overigens (mocht je e daarin comfortabel voelen) ook wat MIJ betreft -- alleen in de README.md als het even klan-- ook rechtstreeks in deze file editen via de GitHub. Maar ik weet niet of anderen dat ook okay vinden.

Ik zal TZT de draft info met meer info die generieker zou kunnen worden gebruikt een andere plek geven. Ik wilde destijds graag de boel op gang helpen qua documentatie en heb dat hier gedaan, omdat dit de belangrijkste repos leek om alles mee vorm te geven.
