### ISSUE TITLE
Informed consent

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/jspsych-vislexdec-vp#14]
Sorry dat ik er nu pas opeens aan denk, maar er moet ergens in het begin ook nog een pagina waar de pp informed consent kan geven. Ik stel me voor, een pagina waar de toestemmingsbrief staat (ik hoop dat we die een beetje kort kunnen houden, dat zijn altijd enorme lappen tekst maar is m.i. niet echt nodig) met daaronder een plek waar de pp kan aanvinken akkoord te gaan met opslag van de data.

Ik moet met de FETC overleggen wat ze perse willen aan info - nu wordt er op de toestemmingverklaring gevraagd naar naam, geboortedatum, handtekening, datum en plaats, het lijkt mij fijn als dat alleen 1 vinkje kan worden.

En dan maar hopen dat we ALS mensen binnen 5 dagen zeggen toch niet akkoord te gaan (nog nooit gebeurd volgens mij), dat we dan op basis van wat we uitvragen in de survey de data van die persoon nog kunnen terugvinden.

**Comment by irisopgithub** [comment]
Update: ik heb overlegd met Marijn, en naar de formulieren op de FETC-website gekeken, en dat is allemaal te ingewikkeld om echt generiek te maken - die consent forms/information letters worden voortdurend aangepast en dan zouden we onze templates ook telkens aan moeten passen. Dus ik stel voor om het voor de templates als volgt te doen: een welkomstpagina waar staat:

Welcome to the online study <name of study and FEtC-H reference number>!
<insert your information letter here; for more information, see the FEtC-H website https://fetc-gw.wp.hum.uu.nl/en/>

Yes, I consent to the use of my answers for scientific research.

met een checkbox. checkbox niet aangevinkt -> door naar de eindpagina. checkbox wel aangevinkt -> door naar het begin van het experiment.

**Comment by jcvanelst** [comment]
okay. ik ga een voorzetje maken met een externe html-pagina met vinkje.

**Comment by jcvanelst** [comment]
Anders opgelost, gedraagt zich nu zoals "met een checkbox. checkbox niet aangevinkt -> door naar de eindpagina. checkbox wel aangevinkt -> door naar het begin van het experiment."

(Overigens gaat ie nu door naar een andere 'end_screen' (end_screen_no_consent, die je eventueel ook aan kunt passen), anders werd het wel heeeeel erg ingewikkeld om in de combinatie te voorzien van: "een enkel vinkje", duidelijk code separatie, en overzichelijke output.
