### ISSUE TITLE
Vingers voor responsen

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/jspsych-vislexdec-vp#15]
"To respond, hit the L key for Yes and the A key for No" -> 

"Put your left index finger on the A key, and your right index finger on the L key. To respond, press the L key for Yes and the A key for No."

**Comment by irisopgithub** [comment]
Er is te weinig tijd, merk ik nu, om tussen het oefenblok (daar moet je op het eind op OK klikken) en het testblok je wijsvingers op de toetsen te zetten. misschien kan daar een instructiescherm komen te staan met nogmaals bovenstaande instructie, die dan vanzelf na een paar seconden overspringt naar het experiment.

**Comment by jcvanelst** [comment]
ja, snap ik, zie ook https://github.com/UiL-OTS-labs/jspsych-vislexdec-vp/issues/16 . Is het in deze niet het handigst om voor een spatiebalk, in plaats van een mouse-buttone te gaan?

**Comment by irisopgithub** [comment]
ik denk het allerbeste om de 'ja'-knop te gebruiken om verder te gaan, dan blijven die wijsvingers op de toetsen, en dan blijft het systeem l/a is ja er ook in. kan dat?

**Comment by jcvanelst** [comment]
met deze commit (in dit template nog even het meest aan te passen ten te testen) https://github.com/UiL-OTS-labs/jspsych-vislexdec-vp-vm/commit/e54b9c5b119665d3154a97291f4802b8eb5234ff en degene daarna heb ik een opzet gemaakt voor de flow met vaste "yes" key.

**Comment by irisopgithub** [comment]
ik weet niet zo goed wat ik hiermee moet - als ik op die link klik kom ik ergens waar ik niet iets kan testen

**Comment by jcvanelst** [comment]
is opgelost. de link is naar de commit waar ik het mee heb doorgevoerd. Voor jou niet zo interessant. Overal is nu de persoonlijk ingestelde (dominante hand)  'ja-knop' de toets om mee door te gaan binnen de experiment (niet-survey etc) context.
