### ISSUE TITLE
Tekst tussen blokken

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/jspsych-vislexdec-vp#16]
"End of the practice part.

If you have any questions at this moment, please ask yourself now.

If not, click OK to continue with the real task."

->

End of the practice part.

If you are ready to continue with the experiment, press < de key die ze gebruiken om 'ja' te zeggen>'

Ik wil graag dat ze hun wijsvingers op de responsknoppen houden, vandaar. (Ik begrijp dat het weinig inclusief is om ervanuit te gaan dat iedereen twee wijsvingers heeft, maar ik stel voor dat we op die slak even geen zout leggen).

**Comment by jcvanelst** [comment]
ja, snap ik. Ik had zelf het idee dat die button response daar erg onhandig is, met oog op precies hetzelfde (vingers op de knoppen) is het een idee om een spatie-balk 'tussen-trial' van te maken?

**Comment by irisopgithub** [comment]
dit issue is volgens mij opgelost
