### ISSUE TITLE
Tekst na afloop

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/jspsych-vislexdec-vp#17]
"Thanks, you're done. Would you like to click OK?"

Kan dit iets worden als

End of the experiment, thank you very much for participating!
en dan een "Close browser tab"-button die de browser tab sluit.

**Comment by jcvanelst** [comment]
Ik heb wel de tekst al aangepast. De close browser tab button moet ik even bespreken, na de data storage functie call is jspsych volgens mij klaar...ik weet ik niet of ik weer een jspsych button in het leven kan roepen na die tijd, maar zal het even met Maarten en Ty checken. Mag het ook een leeg venster zijn, zoals nu geeimplementeerd?

**Comment by irisopgithub** [comment]
ja is prima zoals het nu is
