### ISSUE TITLE
Stimuli are currently not randomised.

### ISSUE THREAD

**Issue by maartenuni** [UiL-OTS-labs/jspsych-vislexdec-vp#2]
Currently the stimuli are loaded as defined in the list.
This feature should be implemented prior to use in the field.

**Comment by jcvanelst** [comment]
can you elaborate on this? The trial setup has options: randomise = true or randomise = false, like here:

    var practice_procedure = {
      timeline:[
        present_fixation, 
        present_prime, 
        present_word, 
        present_feedback
        ],
      timeline_variables: practice_items,
      randomize_order:false 
    };

    var trial_procedure = {
      timeline:[
        present_fixation, 
        present_prime, 
        present_word, 
        ],
      timeline_variables: stimuli.table,
      randomize_order:true 
    };

So, in this case, the practice items are fixed, the others not....

**Comment by maartenuni** [comment]
Hoi Jacco,

Wat je zegt klopt! Dit issue is ouder dan die code. Het is dus inmiddels gefikst. Nu maar hopen dat hier geen randomization met constraints vereist is. Dit is misschien iets om te overleggen met Iris/Marijn.

Toegevoegd in: c5bc110099d6816b4526d27e6c67dcbf0dbd70d4 met de wat onhandige commit message "practice makes perfect".

mvg,

Maarten
