### ISSUE TITLE
key press

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/jspsych-vislexdec-vp#20]
we hebben het hier ooit over gehad in een overleg met ty en maarten erbij, maar ik zie de issue hier niet staan, dus voor de zekerheid in de herhaling: het zou fijn zijn als er naast **"key_press": 76** in de output, ook kan komen te staan welke key dat dan was die er gepresst was (A of L). 

als dat niet kan, misschien in de documentatie een link naar een ascii-tabel? veel studenten zullen echt geen flauw idee hebben van ascii-codes.

**Comment by irisopgithub** [comment]
ik zie nu in de .csv-output van de dataserver dat er wel degelijk een variabele key_chosen_char is A/L weergeeft, maar dat die in de testfase niet 'doorkomt'. dat suggereert dat het niet mogelijk is om dit in de output te krijgen voor de testfase; dan lijkt een ascii-tabel in de documentatie me dus een goede oplossing.

je kunt ook zeggen 'het staat toch **ergens** in de output', maar als je aan het analyseren slaat ga je niet dat deel van de output bekijken waar het in staat.

**Comment by jcvanelst** [comment]
als het goed is gefixt. nu nog 6 andere templates, ik schrijf het op...

**Comment by irisopgithub** [comment]
sorry... ;-/. ik vind het heel lastig om te wennen aan het concept dat je in jspsych blijkbaar bepaalde variabelen niet mee kunt nemen de rest van het experiment in (zelfde met dat de L/A-instantiatie maar 1 keer gebruikt kan worden in de instructies, dat zag ik ook totaal niet aankomen).

**Comment by jcvanelst** [comment]
haha, it's okay hoor. Je moet steeds in de functie bepaalde output-data die niet 'standaard' in een trial (fase) zit expliciet toevoegen. Ik heb me even kwaad gemaakt en hetzefde probleem in de 6 andere ook verholpen. (Na 3 keer ben ik wel gestopt met testen). Ik heb dus 1 echte issue gefixt en 6 niet bestaande issues, slecht voor mn stats ;-)
