### ISSUE TITLE
Output is missing some essential variables.

### ISSUE THREAD

**Issue by maartenuni** [UiL-OTS-labs/jspsych-vislexdec-vp#4]
In the stimulus table is the id of a stimulus. It would be handy to put this in the output. Currently the name of the stimulus is overwritten by the stimulus as handed to jsPscych. Also It is nice to know in which group the participant participated.

For one trial the relevant output is for example:
	{
		"rt": 3277,
		"stimulus": "<p class='stimulus'>palve</p>",
		"key_press": 77,
		"word_type": "NON_WORD",
		"trial_type": "html-keyboard-response",
		"trial_index": 3,
		"time_elapsed": 5594,
		"internal_node_id": "0.0-1.0-2.0",
		"correct": true
	}

I would like to add the raw stimulus only palve in this case, the id and the group/list from the stimulus table from stimuli.js

	{
		"rt": 3277,
		"stimulus": "<p class='stimulus'>palve</p>",
		"key_press": 77,
		"word_type": "NON_WORD",
		"trial_type": "html-keyboard-response",
		"trial_index": 3,
		"time_elapsed": 5594,
		"internal_node_id": "0.0-1.0-2.0",
		"correct": true
                "stim" : "palve",
                "id" : 1,
                "list" : "group1"
	}

**Comment by jcvanelst** [comment]
pushed things that solve things
