### ISSUE TITLE
instructie ontbreekt

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/jspsych-vislexdec-vp#5]
**<p>Dear Participant,</p><p></p><p>Add instructions about which keys to press here.</p>** 

- graag bruikbare instructie van maken, zie voor inspiratie de zep-taak vislexdec_vp (in task.zm)
- zelfde geldt voor instructie na oefenblok.

**Comment by jcvanelst** [comment]
gedaan!
