### ISSUE TITLE
stimulus duration defaults

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/jspsych-vislexdec-vp#7]
Ik vind 80ms wel erg kort om een visual prime aan te bieden als die niet masked is. Ik zou de defaults gebruiken zoals die in de zep-taak waren want die zijn gewoon best zinnig:

// Duration of the interval between two trials.
const dur       INTERTRIAL_INTERVAL             = 1000ms;

// Duration of the fixation symbol presentation.
const dur       FIXATION_DURATION               = 1000ms;

// Duration of the prime stimulus presentation.
const dur       PRIME_DURATION                  = 500ms;

// Duration of the target stimulus presentation.
const dur       STIMULUS_DURATION               = 1000ms;

// Duration of the interval between prime and target.
const dur       PRIME2TARGET_INTERVAL           = 300ms;

// Duration of the feedback presentation.
const dur       FEEDBACK_DURATION               = 1000ms;

// Duration of the response interval. A value of 0ms means there is no
// timeout.
const dur       RESPONSE_DURATION               = 2000ms;       // auto-paced

**Comment by maartenuni** [comment]
Dit kunnen we simpel aanpassen.

**Comment by jcvanelst** [comment]
Nou, in principe, ja, maar het is niet (allemaal) arbitrair!

Ik heb net een push gedaan waarin ik de case hack oplos, maar dit verdient wel aandacht:

JS noemt alles in de standaard response plugins een 'trial', ook al definieer je deze programmatisch als subtrial (zoals hier geimnplementeerd.

De totale duratief vanaf het moment waarop het target woord is aangeboden, is volgens Iris gewenst 2000ms. Het woord moet na 1000 ms verdwijnen uit beeld.

Dit betekent dat het woord moet verdwijnen van het scherm, maar er nog 1000 ms extra tijd moet worden doorgegeven qua trial duur. Ik moet dit qua output enzo nog testen, maar heb nu dus het volgende gedaan:

<stukje in index.html met keyboard response plugin in trial fase "present_word">
...
      trial_duration: WORD_DURATION,
      post_trial_gap: RESPONSE_DURATION_OPTION_ONE, //o my...
...
oh my <deze gebruikt nu een nieuwe "Global" die de 1000 ms toevoegt aan de "trial" fase, zodat het in ieder geval niet binnen een seconde fout word gerekend....

Graag uw gedachten over dit soort keuzes voor een boilerplate, de benaming in globals.js etc.

**Comment by irisopgithub** [comment]
van wie wil je nu precies gedachten waarover jacco? voor mij is je vraag niet duidelijk genoeg om te kunnen beantwoorden, maar misschien was het een vraag aan maarten?

**Comment by jcvanelst** [comment]
never mind, probleem opgelost, ik was niet meer zo scherp gisteren en had de verkeerde dos voor mn neus, er is gewoon een standaard optie voor stimulus vs 'trial' (in ons geval subtrial) optie in de plugin, dus het kon wel 'zeppy'
