### ISSUE TITLE
Stimulus-pseudorandomisatie op basis van criteria

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/jspsych-vislexdec-vp#9]
Het zou erg fijn zijn om stimuli te kunnen pseudorandomiseren op basis van criteria (niet meer dan twee items in conditie X na elkaar, niet meer dan drie experimentele items na elkaar, etc). 

Als dat niet kan doen we het in de cursus op de oldskool-wijze van met de hand een volgorde maken en die ook in de omgekeerde volgorde aanbieden om leereffecten te voorkomen. Dat is wel foutgevoelig, zeker als er meerdere lijsten zijn.

**Comment by maartenuni** [comment]
Dit kan wel, maar dan moeten we zelf even een shuffle swap functie maken en het ala zep doen, veel handwerk, maar zeker niet onmogelijk. Nu laten we jsPsych randomiseren, maar dan is het dus niet pseudo random en kunnen items randomly te vaak achter elkaar aan komen.
Laten we even kijken of dit haalbaar is voor de cursus, ik ga even kijken of ik iets kan bedenken.

**Comment by maartenuni** [comment]
@jcvanelst Wil jij deze proberen of zal ik dat doen?

**Comment by tymees** [comment]
Een dergelijk algoritme heb ik destijds geschreven voor Qualtrics:
https://github.com/UiL-OTS-labs/Qualtrics-Pseudo-Randomizer

Ik heb ook ergens nog een versie daarvan die het ZEP algortime implementeerd, maar die staat daar niet omdat die niet per se beter was dan mijn algoritme. 

Aangezien ik hier dus al wat mee heb gedaan wil ik wel dit implementeren in de utils module?

**Comment by maartenuni** [comment]
Heey Ty,

Dit lijkt mij welkom voor de utils module, het wordt wel lastig om hem generiek te houden. Maar kijk maar even hoever je komt, ik ben benieuwd :-)

**Comment by maartenuni** [comment]
Vergeet trouwens niet de huidige randomisatie uit te zetten :-).

**Comment by jcvanelst** [comment]
Volgens mij is deze gefixt met #13, maar ik heb nog een kleine opmerking:

het standaard gebruiken van pseudorandomisatie levert soms wat nadelen op met templates met de huidige (kleine) hoeveelheid stimuli, vanwege de geringe mogelijkheden tot restricted randomisatie. Dit geeft extra errors, soms. Vermoedelijk vanwege de inner workings van de hoeveelheid tries, maar in feite weet ik het niet. Oplossingsrichtingen: meer stimuli in de template, of niet standaard gebruiken van de uil randomisatie in templates.

**Comment by jcvanelst** [comment]
Of beter uitzoeken, misschien komt het door caching ofzo...

**Comment by tymees** [comment]
Ik denk dat je wel gelijk hebt. Het algoritme probeert maximaal 10x een random volgorde te maken, daarna geeft het op. Tijdens mijn testen was dit genoeg om uit elke valide input (dus, (bijna) evenwichtige groepen van stimuli). Bij een kleiner aantal stimuli ga je sneller tegen dit probleem aanlopen, aangezien je dan sneller een invalide volgorde krijgt. Echter, zeker weten doe ik het niet zonder een voorbeeld van de errors ;)

Er zijn nog twee andere oplossingrichtingen:
- Dit getal 10 hoger of instelbaar maken
- Investeren in het omzetten van ZEP's algoritme.

Dit laatste heb ik destijds onderzocht, maar aangezien dat algoritme niet eindig is (en een hoge big-O heeft) heb ik destijds besloten dat die niet geschikt is voor het web. Oneindige algoritme's kunnen er namelijk voor zorgen dat executie van JS vast blijft haken erop, waardoor de proefpersoon niks ziet. De kans dat dit gebeurd is wel erg klein, moet ik toegeven. 

Dat allemaal gezegd te hebbende: het kunnen togglen van randomisatie via een instelling lijkt me wel een goed idee. Niet iedere onderzoeker wil het, maar het vereist wel een beetje kennis om het toe te voegen voor de onderzoekers die het willen.

**Comment by irisopgithub** [comment]
Ik zou de randomisatie standaard uitzetten inderdaad. En dan maken we wat documentatie over hoe het aangezet moet worden en hoe de criteria aangepast kunnen worden (als dat laatste heel ingewikkeld is, kan de instructie zijn 'neem contact op met'). OK?

**Comment by jcvanelst** [comment]
okay. Zal ik dit punt in de generieke documentatie opnemen?

**Comment by irisopgithub** [comment]
ja, graag!

**Comment by jcvanelst** [comment]
al een tijd geleden gedaan. mag deze Issue gesloten, of willen we hem juist open houden als reminder om het 'handiger instelbaar' te maken?

**Comment by maartenuni** [comment]
As jij weet dat het klopt, dan kan je hem sluiten.

**Comment by maartenuni** [comment]
Ik zou trouwens het handiger instelbaar maken beschouwen als een aparte issue. Hier geld gewoon kan je pseudo randomiseren.

**Comment by jcvanelst** [comment]
oki!
